# section: [title]
# title of your website, your name, be creative
title: "william canin"

# section: [description]
# description of your website, helps a lot in SEO
description: "thoughts on programming, digital wellbeing, linux"

# section: [url]
# [ important!!! ] the base hostname & protocol for your site, e.g. http://example.com
url: "https://williamcanin.github.io"

# section: [baseurl]
# the subpath of your site, e.g. /blog
baseurl: ""

# section: [google]
google:
  site_verification: ""
  analytics:
    enable: false
    id: "" # tracking id, e.g. "UA-200341029-1"
  apps_script:
    url: "https://script.google.com/macros/s/AKfycbySoGUfJlruD_X27cfOKuQ-BUTtfo9I2gDdsjkpRJikXhrJAiNFrd9Okwnc4w6zOXjuhQ/exec"
  recaptcha:
    pubkey: "6Lci194rAAAAAIeSbPaHjMbtf_ShFc44cPAKskY4"

# section: [avatar]
# your website image or logo
avatar:
  open: true
  flip: true
  # note: the image (.jpg|.png) will be searched in the directory: assets/images/
  image:
    front:
      light: wcanin_light.png
      dark: wcanin_dark.png
    back: wcanin_back.png

# section: [home]
home:
  terminal:
    enable: true

# section: [social network]
# note: if you want more, just add more "title" and "url".
socials:
  enable: true
  links:
    - title: github
      url: https://github.com/williamcanin

    - title: gitlab
      url: https://gitlab.com/williamcanin

    - title: youtube
      url: https://www.youtube.com/@WilliamCanin

# section: [blog]
blog:
  search:
    enable: true
  post:
    related_posts:
      enable: true
    comments:
      provider: "giscus" # choose between. options: giscus | disqus.
      giscus:
        repo: "williamcanin/williamcanin.github.io" # your repository, e.g: username/repo-name
        repo_id: "MDEwOlJlcG9zaXRvcnk0MDMyOTUzOQ==" # copied from giscus.app, e.g: R_kgD...
        repo_category: "Comments"
        category_id: "DIC_kwDOAmdhQ84CwLFu" # copied from giscus.app, e.g: DIC_kwD...
        mapping: "pathname"
        reactions_enabled: 1
        theme: "light" # initial theme. default: light
        theme_light: "noborder_light" # light theme. default: noborder_light
        theme_dark: "noborder_gray" # dark theme. default: noborder_gray
        lang: "pt" # en,pt,..
      disqus:
        shortname: "williamcanin" # your shortname disqus

# section: [datelang]
# Here you change the language of the months of the date
datelang:
  format: "%d %b, %Y"
  lang: "pt_PT" # en_US | pt_PT | jp_JP | ch_CH | es_ES | fr_FR | it_IT | de_DE | ru_RU

# section: [Reading time]
reading_time:
  enable: true
  words_per_minute: 180
  message: ["Leia o post em cerca de", "Leia o post em menos de"]
  minutes_label: ["minuto", "minutos"]

# section: [text]
# define names for static text on your website
text:
  menu:
    home: "home"
    blog: "weblog"
    search: "pesquisar"
    tags: "tags"
    feed: "feed"
  home:
    terminal:
      user: "william"
      hostname: "linux"
      welcome: " digite 'help' para começar."
      error: ": comando não encontrado."
      no_socials: "Rede socials não encontrada"
      commands: | # Do not remove the <span>, just change the content
        <span id="mcmd">Comandos</span><span id="mdesc">Descrição</span>
        help -------------- Imprime este menu
        about ------------- Um breve resumo sobre mim
        socials ----------- Links para minhas redes sociais ativas
        clear ------------- Limpar a tela do terminal (ou Precione Esc)
  blog:
    subtitle: "postagens"
    search:
      placeholder: "digite aqui para procurar uma postagem ou Esc para sair"
      button_clean:
        text: "limpar"
      results: "resultados"
      no_results: "Sem resultados"
  page:
    updated_on: "Página atualizada em"
  post:
    date:
      lang: "pt_PT"
    author: "autor"
    related_posts: "postagens relacionadas"
    updated_on: "Postagem atualizada em"
    comments: "comentários"
    pagination:
      newer_text: "recentes"
      counter: ["página", "de"]
      older_text: "velhos"
  tags_posts:
    title: "postagem pela tag"
  contact:
    name:
      placeholder: "seu primeiro e último nome"
    email:
      placeholder: "seu melhor e-mail"
      help: "nunca compartilharei seu e-mail com mais ninguém."
    message:
      placeholder: "escreva sua mensagem aqui"
      status: "enviando..."
      caracters:
        min: 50
        warning:
          title: "Aviso"
          content: "a mensagem deve ter pelo menos 50 caracteres."
      success:
        title: "Envio de mensagem"
        content: "sua mensagem foi enviada com sucesso!"
      error:
        title: "Erro de mensagem"
        content: "algo deu errado ao enviar sua mensagem."
    button:
      text: "enviar!"
    recaptcha:
      warning:
        title: "Aviso"
        content: "Marque a caixa 'Não sou um robô'."
      fail: "Falha na verificação. Recarregue a página e tente novamente."
      error: "Ocorreu um erro ao enviar a mensagem. Tente novamente."
  footer:
    copyright: "© 2015 - 2025 - Todos os direitos reservados."
    message: "thoughts on programming, digital wellbeing, linux"
  error:
    image: https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNXlxYzc5eXp1Nm01cmtldzM5bHhwdzJ2Njk2c2E4b2RkdTBkeGs5eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/c20UV66B7zCWA/giphy.gif
    title: Error 404
    message: |
      Parece que este conteúdo não existe ou foi removido pelo autor.

# section: [lang]
# locality, e.g: en, pt, fr, etc...
lang: pt

# section: [layout]
layout:
  # widh layout. default: 780px
  width: 780px

# section: [footer]
footer:
  top_button:
    enable: true

# section: [maintenance]
maintenance:
  enable: false
  gif: "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExczV3aGMxcnAzdnJ1eWp3cjk5OXdhdTYzdzB0dWVlMGFkbTd2ZDR0ZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/jwKC0qlOoXmcLDB4vC/giphy.gif"
  title: "Em manutenção"
  subtitle: |
    Estamos em manutenção e ainda não temos previsão de retorno.
    Desculpe o transtorno :/

# section: [paginate]
pagination:
  enabled: true
  debug: false
  collection: "posts"
  sort_field: "date"
  sort_reverse: true
  per_page: 50
  permalink: "/page/:num/"
  locale: ""
  title: ":title - Page :num"
  limit: 0

# -------------- there is no need to edit anything from here on down --------------

theme: rawfeed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate-v2
  - rawfeed
feed:
  path: /feed.xml
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      published: true
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag_posts
  permalinks:
    tag: "/blog/tags/:name/"
include: ["_pages"]
permalink: "/blog/:title/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - tmp
  - gulpfile.mjs
  - node_modules
  - .bundle-cache
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - README.md
  - Rakefile
