# section: [title]
# title of your website, your name, be creative
title: "rawfeed"

# section: [description]
# description of your website, helps a lot in SEO
description: "A raw Jekyll theme for minimalists"

# section: [url]
# [ important!!! ] the base hostname & protocol for your site, e.g. http://example.com
url: ""

# section: [baseurl]
# the subpath of your site, e.g. /blog
baseurl: ""

# section: [secutiry] (Content-Security-Policy)
# IMPORTANT!!! If you use any external script from any website in your posts that is not on this
#              list, you must put it here.
#              --- If you don't use it, don't remove what's already there. ---
csp:
  frame-src:
    - https://www.youtube.com
    - https://giscus.app
    - https://disqus.com
  connect-src:
    - https://api.github.com
  img-src:
    - https://media0.giphy.com
    - https://media4.giphy.com

# section: [google]
google:
  site_verification: ""
  analytics:
    enable: false
    id: "" # tracking id, e.g. "UA-200341029-1"
  apps_script:
    url:
  recaptcha:
    pubkey:

# section: [avatar]
# your website image or logo
avatar:
  open: true
  flip: true
  # note: the image (.jpg|.png) will be searched in the directory: assets/images/
  image:
    front:
      light: avatar_light.png
      dark: avatar_dark.png
    back: avatar_back.png

# section: [home]
home:
  terminal:
    enable: true

# section: [social network]
# note: if you want more, just add more "title" and "url".
socials:
  enable: true
  links:
    - title: github
      url: https://github.com/williamcanin/rawfeed

    - title: rubygems
      url: https://rubygems.org/gems/rawfeed

# section: [blog]
blog:
  search:
    enable: true
  post:
    related_posts:
      enable: true
    comments:
      provider: "giscus" # choose between. options: giscus | disqus.
      giscus:
        repo: "" # your repository, e.g: username/repo-name
        repo_id: "" # copied from giscus.app, e.g: R_kgD...
        category_id: "" # copied from giscus.app, e.g: DIC_kwD...
        mapping: "pathname"
        reactions_enabled: 1
        theme: "light" # initial theme. default: light
        theme_light: "noborder_light" # light theme. default: noborder_light
        theme_dark: "noborder_gray" # dark theme. default: noborder_gray
        lang: "en" # en,pt,..
      disqus:
        shortname: "" # your shortname disqus

# section: [datelang]
# Here you change the language of the months of the date
datelang:
  format: "%b %d, %Y"
  lang: "en_US" # en_US | pt_PT | jp_JP | ch_CH | es_ES | fr_FR | it_IT | de_DE | ru_RU

# section: [Reading time]
reading_time:
  enable: true
  words_per_minute: 180
  message: ["Read this post in approximately", "Read this post in less than"]
  minutes_label: ["minute", "minutes"]

# section: [text]
# - define names for static text on your website
# - use emoji unicode 6.0, to have greater compatibility
strings:
  menu:
    home:
      emoji: 🏠&nbsp;
      title: "home"
    blog:
      emoji: 📝&nbsp;
      title: "weblog"
      subtitle: "posts"
    search:
      emoji: 🔍&nbsp;
      title: "search"
    tags:
      emoji: 🏷️&nbsp;
      title: "tags"
    feed:
      emoji: 📰&nbsp;
      title: "feed"
  home:
    terminal:
      user: "rawfeed"
      hostname: "linux"
      welcome: " type 'help' to begin."
      error: ": command not found."
      no_socials: "No socials found"
      commands: | # Do not remove the <span>, just change the content
        <span id="mcmd">Commands</span><span id="mdesc">Description</span>
        help -------------- Print this menu
        about ------------- A brief summary about 'rawfeed'
        socials ----------- Links to my active social networks
        clear ------------- Clear the terminal screen (or Press Esc)
  blog:
    subtitle: "posts"
    search:
      placeholder: "type here to search for a post or Esc to exit"
      button_clean:
        text: "clean"
      results: "results"
      no_results: "No results found"
  page:
    updated_on: "Page updated on"
  post:
    author: "author"
    related_posts: "related posts"
    updated_on: "Post updated on"
    comments: "comments"
    pagination:
      newer_text: "newer posts"
      counter: ["page", "of"]
      older_text: "older posts"
  tags_posts:
    title: "posts by tag"
  contact:
    name:
      placeholder: "first and last name"
    email:
      placeholder: "your best email address"
      help: "we'll never share your email with anyone else."
    message:
      placeholder: "write your message here"
      status: "sending...wait"
      caracters:
        min: 50
        warning:
          title: "Warning"
          content: "the message must have at least 50 characters."
      success:
        title: "Message sent"
        content: "your message has been sent successfully!"
      error:
        title: "Error"
        content: "something went wrong while sending your message."
    button:
      text: "send!"
    recaptcha:
      warning:
        title: Warning
        content: "Please tick the 'I'm not a robot' box."
      fail: "Verification failed. Please reload the page and try again."
      error: "An error occurred while sending the message. Please try again."
  footer:
    copyright:
      since: 2025
      message: "All rights reserved."
    message: "Created by: William C. Canin"
  error:
    image: https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExNXlxYzc5eXp1Nm01cmtldzM5bHhwdzJ2Njk2c2E4b2RkdTBkeGs5eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/c20UV66B7zCWA/giphy.gif
    title: Error 404
    message: |
      It appears this content does not exist or has been removed by the author.

# section: [lang]
# locality, e.g: en, pt, fr, etc...
lang: en

# section: [layout]
layout:
  # widh layout. default: 780px
  width: 780px

# section: [footer]
footer:
  top_button:
    enable: true

# section: [maintenance]
maintenance:
  enable: false
  gif: "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExczV3aGMxcnAzdnJ1eWp3cjk5OXdhdTYzdzB0dWVlMGFkbTd2ZDR0ZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/jwKC0qlOoXmcLDB4vC/giphy.gif"
  title: "Under maintenance"
  subtitle: |
    We are undergoing maintenance, with no return date yet.
    Sorry for the inconvenience :/

# section: [paginate]
pagination:
  enabled: true
  debug: false
  collection: "posts"
  sort_field: "date"
  sort_reverse: true
  per_page: 50
  permalink: "/page/:num/"
  locale: ""
  title: ":title - Page :num"
  limit: 0

# -------------- there is no need to edit anything from here on down --------------

theme: rawfeed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate-v2
  - rawfeed
feed:
  path: /feed.xml
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      published: true
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag_posts
  permalinks:
    tag: "/blog/tags/:name/"
include: ["_pages"]
permalink: "/blog/:title/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - gulpfile.mjs
  - node_modules
  - .bundle-cache
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - README.md
  - Rakefile
